### ISSUE TITLE
Fix UI of Club21

### ISSUE THREAD

**Issue by kaizvn** [Rev-Tech/club21js#41]

**Comment by kaizvn** [comment]
Refactor dashboard as Card-wallet
Remove overflow of verticalbar.


![Screen Shot 2020-02-24 at 2 39 57 PM](https://user-images.githubusercontent.com/3988087/75136030-ec620d00-5715-11ea-8497-3dd25b43e427.png)


Fix layout of table in purchase club21 NFT page.
![Screen Shot 2020-02-24 at 2 44 22 PM](https://user-images.githubusercontent.com/3988087/75136035-ef5cfd80-5715-11ea-9ed2-6b65d93f0de6.png)

**Comment by kaizvn** [comment]
Mobile UI: with of language should be enough to show flag only.
Hide fullscreen button.

**Comment by ttduongtran** [comment]
<img width="780" alt="Screen Shot 2020-02-24 at 16 29 37" src="https://user-images.githubusercontent.com/26478300/75141236-208ffa80-5723-11ea-9fa0-63baca67cb04.png">
<img width="100" alt="Screen Shot 2020-02-24 at 16 28 49" src="https://user-images.githubusercontent.com/26478300/75141242-238aeb00-5723-11ea-8981-e8d1550032d9.png">
<img width="213" alt="Screen Shot 2020-02-24 at 16 27 55" src="https://user-images.githubusercontent.com/26478300/75141244-24238180-5723-11ea-9613-d8470fd084e8.png">

**Comment by ttduongtran** [comment]
![image](https://user-images.githubusercontent.com/26478300/75141738-3225d200-5724-11ea-8c7d-6dde0fcf4da7.png)

**Comment by ttduongtran** [comment]
![image](https://user-images.githubusercontent.com/26478300/75142020-c2fcad80-5724-11ea-9475-06bc05d790d8.png)

**Comment by ttduongtran** [comment]
http://52.221.238.157/b21_purchases
![image](https://user-images.githubusercontent.com/26478300/75142498-ccd2e080-5725-11ea-9642-f780e8820954.png)

**Comment by ttduongtran** [comment]
http://52.221.238.157/payment

![image](https://user-images.githubusercontent.com/26478300/75142815-6f8b5f00-5726-11ea-9294-effb054fb43a.png)

![image](https://user-images.githubusercontent.com/26478300/75142893-9cd80d00-5726-11ea-86da-161d090447b0.png)

**Comment by ttduongtran** [comment]
Navigation: haven't set active 
![image](https://user-images.githubusercontent.com/26478300/75143159-2091f980-5727-11ea-97ce-114727e82e19.png)

**Comment by ttduongtran** [comment]
> Navigation: haven't set active
> ![image](https://user-images.githubusercontent.com/26478300/75143159-2091f980-5727-11ea-97ce-114727e82e19.png)

Thai is working on it
#38
