### ISSUE TITLE
Fix Ui of Club21 on Mobile

### ISSUE THREAD

**Issue by kaizvn** [Rev-Tech/club21js#42]
1. Not display currency
target link: http://52.221.238.157/compound

![E4BB4AFC-74CF-47BF-A5D9-09CA7057DA7E](https://user-images.githubusercontent.com/26478300/75138738-87121a00-571d-11ea-8d77-34564a2a1697.jpeg)

2. Check spacing and align
target link: http://52.221.238.157/b21_purchases

![6155BBE2-5B1E-4294-A15E-FC8A1EE48487](https://user-images.githubusercontent.com/26478300/75138806-b6c12200-571d-11ea-9114-fec44566ffcf.jpeg)

*text override
![image](https://user-images.githubusercontent.com/26478300/75140003-9cd50e80-5720-11ea-9ce8-8711ea985e0b.png)

*font-size, icons, spacing
<img width="779" alt="Screen Shot 2020-02-24 at 16 22 12" src="https://user-images.githubusercontent.com/26478300/75140902-68fae880-5722-11ea-91ad-164720eec156.png">

**Comment by ttduongtran** [comment]
![1C2A9B07-9F3E-4C6C-8A0E-3372F3BDA0A2](https://user-images.githubusercontent.com/26478300/75139910-7020f700-5720-11ea-8fe1-f07f4fd463be.jpeg)
![C93C3643-1C95-4CD1-A954-4ACBB4E53AC4](https://user-images.githubusercontent.com/26478300/75139919-731be780-5720-11ea-8859-f3854eed38b5.jpeg)
![CAF72A0B-085B-46CB-BB55-91B81CB31E5C](https://user-images.githubusercontent.com/26478300/75139921-744d1480-5720-11ea-85db-3b0abc8c8a7d.png)

**Comment by thaind97git** [comment]
![image](https://user-images.githubusercontent.com/42630357/75328375-83fb6300-58b0-11ea-82af-f25bfb6803e0.png)

**Comment by trgianghuynh1808** [comment]
![Screenshot from 2020-02-27 11-29-42](https://user-images.githubusercontent.com/49706073/75412297-9f1fae80-5954-11ea-8231-34b836c31e64.png)
